version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directories:
      - "/infra/aws"
      - "/infra/gcp"
      - "/infra/azure"
    schedule:
      interval: "weekly"
